name: my_blog
description: simple blog application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  auto_route: ^1.0.0-beta.7
  font_awesome_flutter: ^8.11.0
  url_launcher: ^5.7.10
  url_launcher_web:
  timeago: ^2.0.29
  google_fonts:
  # remove the  "#" from url
  # url_strategy: ^0.1.1
  # dio: ^3.0.10
  cached_network_image: ^2.5.0

  firebase_core: "0.7.0"
  firebase_core_web: ^0.2.1+3

  # firebase_analytics: ^5.0.16
  # firebase_analytics_web: ^0.1.1

  # cloud_firestore: ^0.16.0
  # cloud_firestore_web: ^0.3.0+1
  
  # firebase_auth: ^0.20.0+1
  # firebase_auth_web: ^0.3.2+6
  # webview_flutter: ^1.0.7
  # easy_web_view: ^1.3.1
  flutter_markdown: ^0.5.2
  flutter_queen:
    git:
      url: git://github.com/maxzod/flutter_queen.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/posts/
